### ISSUE TITLE
Spider legs move from the initial position

### ISSUE THREAD

**Issue by szyna** [xav9211/Spider-speeder#32]
After few minutes of gameplay legs randomly changes position (we're not talking about rotation!!).
It MAY be caused by either float's inaccuracy or by explosions (that are my guesses).

**Comment by dextero** [comment]
Explosions only modify camera offset, so that shouldn't ever be an issue.

If that's really because of floats, then we're a bit screwed. What can we do? Reset legs' position at each frame?

**Comment by szyna** [comment]
You're right, it's not the problem with the explosions (just experienced this bug with no mobs on the map, it happened after(most likely, spider is too fast) the collision with wall while using a web). Still waiting for someone to find out how to reproduce it.

**Comment by dextero** [comment]
Fixed by #57
